### ISSUE TITLE
Carousel not working when the project is deployed to AppEngine

### ISSUE THREAD

**Issue by lbhtran** [PolymerLabs/polymer-2-carousel#22]
Hi team,

I'm following the tutorial on polymer-2-carousel. However, when I deploy this to AppEngine to test out touch input, it only shows 1 photo. Could you please suggest where I've gone wrong? 

The page I deployed it to is https://learn-polymer-image-carousel.appspot.com/

**Comment by keanulee** [comment]
It appears that view-source:https://learn-polymer-image-carousel.appspot.com/my-carousel.html is loading the contents of index.html and not [my-carousel.html](https://github.com/PolymerLabs/polymer-2-carousel/blob/master/step-09/my-carousel.html). Make sure App Engine is configured correctly. For example, you may need to specify handlers for my-carousel.html and my-mixin.html:

app.yaml
```yaml
- url: /my-carousel.html
  static_files: my-carousel.html
  upload: my-carousel.html

- url: /my-mixin.html
  static_files: my-mixin.html
  upload: my-mixin.html
```
